"""Initial migration

Revision ID: 4ddcb7ca4d93
Revises: 
Create Date: 2023-09-08 19:24:19.027715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddcb7ca4d93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract', 'Owner', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'owner_id')
    # ### end Alembic commands ###
