# Generated by Django 4.1.2 on 2022-10-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_full_name', models.CharField(max_length=45)),
                ('owner_cpf', models.IntegerField()),
                ('owner_rg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_full_name', models.CharField(max_length=45)),
                ('tenant_cpf', models.IntegerField()),
                ('tenant_rg', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_adress', models.CharField(max_length=50)),
                ('property_adress_number', models.CharField(max_length=4)),
                ('property_adress_complement', models.CharField(max_length=10)),
                ('property_adress_district', models.CharField(max_length=20)),
                ('property_adress_city', models.CharField(max_length=20)),
                ('located', models.BooleanField(default=False)),
                ('property_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locationContractApp.tenant')),
            ],
        ),
    ]
